name: maven_test_artifact

# run maven tests and upload results as an artifact
# can be run from a pr

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

  workflow_dispatch:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

jobs:
  maven_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          cache: 'maven'
          distribution: 'temurin'

      - name: "Test ${{ inputs.context }}"
        #working-directory: ${{ inputs.context }}
        #run: mvn --batch-mode --activate-profiles prod -Dangular.env=qa -Dmaven.test.failure.ignore=true test
        run: |
          mvn -B verify -Dangular.env=qa -Pprod --file ${{ inputs.context }}/pom.xml

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: ${{ inputs.context }}
          path: ${{ inputs.context }}/target/surefire-reports/*.xml
