name: pre_commit_ci_lite

# NOTE: this action will only apply changes on a pr action

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Open JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ~/.m2
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      # lockdown all 3rd party repos to git shas
      - uses: pre-commit/action@5f528da5c95691c4cf42ff76a4d10854b62cbb82

      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()

