name: unit_tests_artifact

# Run tests and upload the results as an artifact
# Can be run from a unprivileged pull_request action
# Reporting is done in the pr_completed.yml workflow

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'version tag to use'
        required: false
        default: "latest"
        type: string

  workflow_dispatch:
    inputs:
      version_tag:
        description: 'version tag to use'
        required: false
        default: "latest"
        type: string

jobs:

  tst_assertion_service:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      context: assertion-service

  tst_discovery_service:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      context: discovery-service

  tst_gateway:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      context: gateway

  tst_member_service:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      context: member-service

  tst_user_service:
    uses: ./.github/workflows/maven_test_artifact.yml
    with:
      context: user-service

